### ISSUE TITLE
To add

### ISSUE THREAD

**Issue by randomaccess3** [randomaccess3/detections#9]
https://palant.info/2023/06/08/another-cluster-of-potentially-malicious-chrome-extensions/

**Comment by randomaccess3** [comment]
https://palant.info/2023/06/14/why-browser-extension-games-need-access-to-all-websites/

**Comment by randomaccess3** [comment]
https://www.malwarebytes.com/blog/threat-intelligence/2023/07/criminals-target-businesses-with-malicious-extension-for-metas-ads-manager-and-accidentally-leak-stolen-accounts

**Comment by randomaccess3** [comment]
https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/new-rilide-stealer-version-targets-banking-data-and-works-around-google-chrome-manifest-v3/

**Comment by nicoleahmed** [comment]
this is palant's overarching list https://raw.githubusercontent.com/palant/malicious-extensions-list/main/list.txt

**Comment by randomaccess3** [comment]
Thanks!

**Comment by randomaccess3** [comment]
https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/new-rilide-stealer-version-targets-banking-data-and-works-around-google-chrome-manifest-v3/#rilide_loaders_itw_urls

**Comment by randomaccess3** [comment]
https://www.trendmicro.com/en_us/research/23/h/profile-stealers-spread-via-llm-themed-facebook-ads.html

**Comment by randomaccess3** [comment]
https://www.welivesecurity.com/2013/07/30/versatile-and-infectious-win64expiro-is-a-cross-platform-file-infector/

**Comment by randomaccess3** [comment]
https://decoded.avast.io/anhho/chasing-chaes-kill-chain/

**Comment by randomaccess3** [comment]
https://blog.morphisec.com/chaes4-new-chaes-malware-variant-targeting-financial-and-logistics-customers

**Comment by randomaccess3** [comment]
https://www.bleepingcomputer.com/news/security/backdoored-chrome-extension-installed-by-200-000-roblox-players/

**Comment by randomaccess3** [comment]
https://reasonlabs.com/research/new-widespread-extension-trojan-malware-campaign
